services:
  mysql-server:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: music
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --save 60 1 --loglevel warning

  elastic:
    image: elasticsearch:8.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elastic:/usr/share/elasticsearch/data

volumes:
  db:
  redis:
  elastic: